name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make
        run: LLANG_VERSION=${{ inputs.release }} make llang-linux-x64

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "llang-*-linux-x64.zip"
          generateReleaseNotes: true
          tag: ${{ inputs.release_version }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into ghcr.io
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          push: true
          tags: ghcr.io/juliojimenez/l:${{ inputs.release_version }}
          labels: ${{ steps.meta.outputs.labels }}
