name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release version"
        required: true

permissions:
  packages: write
  contents: write

jobs:
  build:
    name: Build llang
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make
        run: LLANG_VERSION=${{ inputs.release }} make llang-linux-amd64

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "llang-*-linux-amd64"
          generateReleaseNotes: true
          tag: ${{ inputs.release }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into ghcr.io
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6.2.0
        with:
          context: .
          push: true
          tags: ghcr.io/juliojimenez/l:${{ inputs.release }}
          labels: ${{ steps.meta.outputs.labels }}
