name: Tests

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make
        run: make llang-tests

      - name: Run Tests
        run: ./llang-tests
